---
- name: Atualizar cache de pacotes
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Instalar pacotes b치sicos
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
      - python3-pip
      - jq
    state: present

- name: Desabilitar swap
  shell: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Remover swap do fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Configurar m칩dulos do kernel
  copy:
    content: |
      overlay
      br_netfilter
    dest: /etc/modules-load.d/k8s.conf

- name: Carregar m칩dulos do kernel
  community.general.modprobe:
    name: "{{ item }}"
  loop:
    - overlay
    - br_netfilter

- name: Configurar par칙metros sysctl
  copy:
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1
    dest: /etc/sysctl.d/k8s.conf
  notify: reload sysctl

- name: Configurar timezone
  timezone:
    name: America/Sao_Paulo
