---
- name: Criar diretório de keyrings do APT
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Baixar e instalar a chave GPG do Kubernetes
  ansible.builtin.shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Adicionar repositório Kubernetes
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"
    state: present
    filename: kubernetes

- name: Instalar pacotes Kubernetes
  apt:
    name:
      - kubelet={{ kubernetes_version }}-1.1
      - kubeadm={{ kubernetes_version }}-1.1
      - kubectl={{ kubernetes_version }}-1.1
    state: present
    update_cache: yes

- name: Manter pacotes Kubernetes na versão atual
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl

- name: Habilitar kubelet
  systemd:
    name: kubelet
    enabled: yes
