---
- name: Adicionar chave GPG do Kubernetes
  apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
    keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    state: present

- name: Adicionar repositório Kubernetes
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"
    state: present
    filename: kubernetes

- name: Instalar pacotes Kubernetes
  apt:
    name:
      - kubelet={{ kubernetes_version }}-1.1
      - kubeadm={{ kubernetes_version }}-1.1
      - kubectl={{ kubernetes_version }}-1.1
    state: present
    update_cache: yes

- name: Manter pacotes Kubernetes na versão atual
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl

- name: Habilitar kubelet
  systemd:
    name: kubelet
    enabled: yes
