---
- name: Criar diretório de keyrings do APT
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Baixar e instalar a chave GPG do Docker
  ansible.builtin.shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: Adicionar repositório Docker
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Instalar Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Configurar containerd
  template:
    src: containerd-config.toml.j2
    dest: /etc/containerd/config.toml
  notify:
    - restart containerd

- name: Adicionar usuário ao grupo docker
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Habilitar e iniciar Docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Habilitar e iniciar containerd
  systemd:
    name: containerd
    enabled: yes
    state: started
